"""Disclaimer agent: Append mandatory SEBI/regulatory disclaimers."""

from datetime import datetime
from ..agents.state import ArthAgentState

# Hardcoded SEBI and regulatory disclaimer
MANDATORY_DISCLAIMER = """
⚠️  MANDATORY DISCLAIMER

This financial plan is generated by an AI system and is NOT a substitute for professional 
financial advice from a licensed Financial Advisor. Please note:

1. REGULATORY COMPLIANCE: This plan is not licensed advice under SEBI (Investment Advisers) 
   Regulations, 2013. Consult a SEBI-registered investment advisor for portfolio recommendations.

2. TAX GUIDANCE: Tax calculations are based on FY 2025-26 regulations and your provided information. 
   Consult a Chartered Accountant (CA) or tax professional before filing returns. Tax laws may change.

3. NO GUARANTEE: Past returns do not guarantee future performance. Market conditions, interest rates, 
   inflation, and personal circumstances can significantly impact outcomes.

4. PERSONAL CIRCUMSTANCES: This plan is generic. Your actual tax liability, investment returns, and 
   retirement needs may differ based on:
   - Specific loan terms, insurance policies, and investment fund details
   - Changes in income, expenses, or life events
   - Regulatory changes issued after this plan's date
   - Individual risk tolerance and time horizon

5. PRODUCT RESEARCH: Before investing in any mutual fund, NPS, or insurance product mentioned, 
   conduct independent due diligence. Review prospectuses, fact sheets, and fund manager track records.

6. REGULAR REVIEW: Financial plans require annual review based on life changes, market conditions, 
   and regulatory updates. Review this plan with a qualified advisor at least annually.

7. THIRD-PARTY DATA: Investment data (fund overlaps, expense ratios, XIRR calculations) is sourced 
   from publicly available information and may have reconciliation timing differences.

LIMITATION OF LIABILITY: ArthAgent and developers assume no responsibility for investment losses, 
tax penalties, or opportunity costs resulting from this plan's implementation or reliance thereon.

By using this plan, you acknowledge that you understand these disclaimers and have sought 
independent professional advice where necessary.

Generated: {timestamp}
"""


async def disclaimer_agent(state: ArthAgentState) -> ArthAgentState:
    """DisclaimerAgent node: Append hardcoded mandatory disclaimers."""
    state["current_step"] = "disclaimer_agent"
    state["audit_log"].append({
        "timestamp": datetime.utcnow().isoformat(),
        "step": "disclaimer_agent",
        "status": "started",
    })

    try:
        timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
        disclaimer = MANDATORY_DISCLAIMER.format(timestamp=timestamp)

        # Append disclaimer to final plan
        if state.get("final_plan"):
            state["final_plan"]["disclaimer"] = disclaimer

        state["disclaimer_appended"] = True

        state["audit_log"].append({
            "timestamp": datetime.utcnow().isoformat(),
            "step": "disclaimer_agent",
            "status": "completed",
            "detail": "Mandatory disclaimers appended",
        })

    except Exception as e:
        state["error"] = f"Disclaimer append error: {str(e)}"
        state["audit_log"].append({
            "timestamp": datetime.utcnow().isoformat(),
            "step": "disclaimer_agent",
            "status": "error",
            "detail": str(e),
        })

    return state
